import { useState } from 'react';
import { assessSeller, defaultBrief, exampleSellers, recommendSeller, type Brief, type IconStyle } from './scenario-demo.ts';
import './scenario-demo.css';
function SampleIcon({ style, name }: { style: IconStyle; name: 'spark' | 'calendar' | 'people' }) {
  return <svg viewBox="0 0 32 32" fill={style === 'solid' ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth={style === 'solid' ? '.8' : '1.7'} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{style === 'duotone' && <rect x="2" y="2" width="28" height="28" rx="9" fill="currentColor" opacity=".18" stroke="none"/>}{name === 'spark' ? <path d="m16 4 3.5 8.5L28 16l-8.5 3.5L16 28l-3.5-8.5L4 16l8.5-3.5Z"/> : name === 'calendar' ? <><rect x="6" y="8" width="20" height="19" rx="3"/><path d="M11 4v8M21 4v8M6 15h20" stroke={style === 'solid' ? '#101c30' : 'currentColor'}/></> : <><circle cx="13" cy="11" r="4"/><path d="M5 26v-3a8 8 0 0 1 16 0v3ZM22 7a4 4 0 0 1 0 8m3 4a7 7 0 0 1 3 7"/></>}</svg>;
}
export function ScenarioDemo() {
  const [brief, setBrief] = useState<Brief>(defaultBrief);
  const [selectedId, setSelectedId] = useState('lucent');
  const [reviewed, setReviewed] = useState(false);
  const [showDraft, setShowDraft] = useState(false);
  const selected = exampleSellers.find(s => s.id === selectedId)!;
  const recommended = recommendSeller(brief);
  const assessment = assessSeller(selected, brief);
  function updateBrief(change: Partial<Brief>) { setBrief(current => ({ ...current, ...change })); setReviewed(false); }
  function select(id: string) { setSelectedId(id); setReviewed(false); }
  return <div className="scenario-demo">
    <div className="scenario-context"><span className="demo-badge">Scenario demo</span><span>Local examples · Rule-based match</span></div>
    <section className="brief-panel" aria-labelledby="brief-title"><div><p className="scenario-step">01 / TASK BRIEF</p><h2 id="brief-title">Build an event landing page</h2><p>Find a consistent icon pack.</p></div><div className="brief-controls"><label>Style<select aria-label="Style" value={brief.style} onChange={e => updateBrief({ style: e.target.value as IconStyle })}><option value="outline">Outline</option><option value="solid">Solid</option><option value="duotone">Duotone</option></select></label><label>Budget<select aria-label="Budget" value={brief.budget} onChange={e => updateBrief({ budget: Number(e.target.value) })}><option value="0">0 demo credits</option><option value="1">1 demo credit</option><option value="3">3 demo credits</option></select></label><label className="brief-check"><input type="checkbox" checked={brief.editable} onChange={e => updateBrief({ editable: e.target.checked })}/> Editable SVG</label><label className="brief-check"><input type="checkbox" checked={brief.commercial} onChange={e => updateBrief({ commercial: e.target.checked })}/> Commercial use</label></div></section>
    <section aria-labelledby="compare-title"><div className="scenario-section-head"><div><p className="scenario-step">02 / COMPARE SELLERS</p><h2 id="compare-title">One task. Three options.</h2></div><span className="scenario-caption">All sellers and prices are examples.</span></div><div className="seller-grid">{exampleSellers.map(seller => { const result = assessSeller(seller, brief); return <article className={`seller-option ${selectedId === seller.id ? 'selected' : ''}`} key={seller.id}><div className="seller-option-head"><span>Example seller</span>{recommended?.id === seller.id && <span className="match-badge">Rule match</span>}</div><div className={`icon-swatch swatch-${seller.style}`}><SampleIcon style={seller.style} name="calendar"/><SampleIcon style={seller.style} name="people"/><SampleIcon style={seller.style} name="spark"/></div><h3>{seller.name}</h3><p className="pack-name">{seller.pack}</p><dl><div><dt>Style / format</dt><dd>{seller.style} · {seller.format}</dd></div><div><dt>License claim</dt><dd>Commercial · Unverified</dd></div><div><dt>Demo price</dt><dd>{seller.credits === 0 ? 'Free · 0 credits' : `${seller.credits} ${seller.credits === 1 ? 'credit' : 'credits'}`}</dd></div></dl><div className="seller-option-foot"><span>{result.matches}/4 conditions</span><button aria-pressed={selectedId === seller.id} onClick={() => select(seller.id)}>{selectedId === seller.id ? 'Selected' : 'Select'}<span className="sr-only"> {seller.name}</span></button></div></article>; })}</div><p className="catalog-note">Seller-stated license claims are unverified. No live search or AI call.</p></section>
    <section className="selection-panel" aria-labelledby="selection-title"><div className="selection-summary"><p className="scenario-step">03 / REVIEW SELECTION</p><h2 id="selection-title">{selected.name}</h2><p>{assessment.allMatch ? 'Matches the requested conditions.' : 'Some conditions do not match.'}</p><ul className="selection-checks">{assessment.checks.map(c => <li key={c.label}><span className={c.matches ? 'condition-match' : 'condition-miss'}>{c.matches ? '✓' : '—'}</span>{c.detail}</li>)}</ul><div className="scenario-actions"><button className="primary" onClick={() => setReviewed(true)}>Review selection</button><button onClick={() => setShowDraft(value => !value)}>{showDraft ? 'Hide draft' : 'Preview draft'}</button></div></div><div className="integration-status" aria-live="polite"><span className="integration-label">LOCAL REVIEW</span><h3>{reviewed ? assessment.allMatch ? 'Conditions match' : 'Needs a different option' : 'Not reviewed'}</h3><dl><div><dt>Integration</dt><dd>Not connected</dd></div><div><dt>Purchase</dt><dd>Not completed</dd></div><div><dt>License</dt><dd>Unverified</dd></div></dl><p>No payment or resource delivery.</p>{!recommended && <p>No seller meets every condition.</p>}</div></section>
    {showDraft && <section className="draft-section" aria-labelledby="draft-title"><div className="scenario-section-head"><div><p className="scenario-step">04 / SAMPLE DRAFT</p><h2 id="draft-title">Your page, with {selected.style} icons</h2></div><span className="demo-badge">Bundled sample · Not purchased</span></div><div className={`event-draft draft-${selected.style}`}><div className="draft-nav"><strong>gather.</strong><span>Sample event page</span></div><div className="draft-hero"><span>MAKE / MEET / CREATE</span><h3>A day for<br/>bright ideas.</h3><p>Meet people. Make something new.</p><span className="draft-cta">Join the gathering <span aria-hidden="true">↗</span></span></div><div className="draft-features">{(['calendar','people','spark'] as const).map((name,i) => <div key={name}><SampleIcon style={selected.style} name={name}/><h4>{['One shared day','Good company','Fresh ideas'][i]}</h4><p>{['Talks & workshops','Small-group sessions','Make room to explore'][i]}</p></div>)}</div></div><p className="catalog-note">Bundled artwork previews a style. It is not a seller download or a finished purchase.</p></section>}
  </div>;
}
