import {describe,it,expect,vi} from 'vitest';
import { TaskGrantClient } from './task-grant-client.ts';
import {TASK_GRANT_REVISION,isTaskGrantStatus,type TaskGrantInput,type TaskGrantStatus} from '../../../shared/task-grant.ts';
import {RESOURCE_PATH,TEST_NETWORK,TEST_USDC} from '../../../shared/contracts.ts';
// All data are injected synthetic local test values; no service or wallet calls.
const input:TaskGrantInput={totalBudgetAtomic:'5000',perTransactionAtomic:'1000',validForMinutes:30,confirmed:true};
const context={taskId:'report-task',taskName:'Test-only report',agentId:'test-agent',agentName:'Test-only executor',account:'0x1111111111111111111111111111111111111111',payTo:'0x2222222222222222222222222222222222222222',network:TEST_NETWORK,asset:TEST_USDC,resource:RESOURCE_PATH} as const;
function status(saved=false):TaskGrantStatus{return {contractRevision:TASK_GRANT_REVISION,context,canSave:!saved,grant:saved?{...input,grantId:'grant-test-only',version:1,taskId:context.taskId,agentId:context.agentId,account:context.account,payTo:context.payTo,network:TEST_NETWORK,asset:TEST_USDC,resource:RESOURCE_PATH,createdAt:'2026-09-27T00:00:00Z',expiresAt:'2026-09-27T00:30:00Z'}:null,paymentEnabled:false,executionConnected:false,accounting:{state:'not_connected',spentAtomic:null,reservedAtomic:null,availableAtomic:null,walletBalanceAtomic:null}};}
function deferred(){let resolve!:(x:unknown)=>void;const promise=new Promise<unknown>(r=>{resolve=r;});return {promise,resolve};}
describe('task permission client with offline injected transport',()=>{
 it('only queries on refresh and needs known state before save',async()=>{const request=vi.fn(async()=>status());const c=new TaskGrantClient(()=>{},request);await c.save(input);expect(request).not.toHaveBeenCalled();await c.refresh();expect(request).toHaveBeenCalledExactlyOnceWith(undefined);});
 it('sends only confirmed permission fields and retains saved state',async()=>{const request=vi.fn(async(body?:TaskGrantInput)=>status(!!body));const c=new TaskGrantClient(()=>{},request);await c.refresh();await c.save(input);expect(request).toHaveBeenLastCalledWith(input);expect(c.state.status?.grant?.grantId).toBe('grant-test-only');await c.save(input);expect(request).toHaveBeenCalledTimes(2);});
 it('blocks double save while pending',async()=>{const p=deferred();const request=vi.fn((body?:TaskGrantInput)=>body?p.promise:Promise.resolve(status()));const c=new TaskGrantClient(()=>{},request);await c.refresh();const save=c.save(input);await c.save(input);expect(request).toHaveBeenCalledTimes(2);p.resolve(status(true));await save;});
 it.each(['throw','shape','other-account','other-budget'])('clears uncertain response without retry: %s',async kind=>{const request=vi.fn(async(body?:TaskGrantInput)=>{if(!body)return status();if(kind==='throw')throw new Error('private secret');if(kind==='shape')return {paymentEnabled:true};const s=status(true);if(kind==='other-account'){s.context={...s.context,account:context.payTo};s.grant!.account=context.payTo;}if(kind==='other-budget')s.grant!.totalBudgetAtomic='9000';return s;});const c=new TaskGrantClient(()=>{},request);await c.refresh();await c.save(input);await c.save(input);expect(request).toHaveBeenCalledTimes(2);expect(c.state.status).toBeNull();expect(c.state.message).toContain('未确认');expect(c.state.message).not.toContain('private secret');});
 it('ignores a result after disposal',async()=>{const p=deferred(),changed=vi.fn(),c=new TaskGrantClient(changed,()=>p.promise);const work=c.refresh();c.dispose();const calls=changed.mock.calls.length;p.resolve(status());await work;expect(changed).toHaveBeenCalledTimes(calls);});
 it('does not submit unconfirmed or injected fields',async()=>{const request=vi.fn(async()=>status());const c=new TaskGrantClient(()=>{},request);await c.refresh();await c.save({...input,confirmed:false} as never);await c.save({...input,account:context.payTo} as never);expect(request).toHaveBeenCalledTimes(1);});
});
describe('frozen permission envelope',()=>{
 it('keeps accounting unknown and rejects fabricated amounts or execution capability',()=>{expect(isTaskGrantStatus(status())).toBe(true);expect(isTaskGrantStatus(status(true))).toBe(true);const s=status();expect(isTaskGrantStatus({...s,paymentEnabled:true})).toBe(false);expect(isTaskGrantStatus({...s,accounting:{...s.accounting,spentAtomic:'0'}})).toBe(false);});
});
